spring:
  application:
    name: order-service
  cloud:
    consul:
      host: consul
      port: 8500

server:
  port: 8904

---
spring:
  profiles: dev
  application:
    name: order-service
  h2:
    console:
      enabled: true
  cloud:
    consul:
      host: localhost
      port: 8500

server:
  port: 8904
