version: '3'

services:
  consul:
    image: consul
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    command: "agent -server -client 0.0.0.0 -ui -bootstrap-expect 1"

  db:
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  gateway-service:
    image: ${DOCKER_REGISTRY_URL}/gateway/gateway:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8900:8900
    depends_on:
      - consul

  authentication-service:
    image: ${DOCKER_REGISTRY_URL}/authentication/authentication:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - consul
      - db

  user-service:
    image: ${DOCKER_REGISTRY_URL}/user/user:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - consul
      - db

  product-service:
    image: ${DOCKER_REGISTRY_URL}/product/product:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - consul
      - db

  order-service:
    image: ${DOCKER_REGISTRY_URL}/order/order:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - consul
      - db
